#!/bin/bash
#此脚本用来 DIY ROM 用
#制作者：陈云
#写于2014年3月 窝窝
#写于2014年4月 深圳语信公司
#写于2014年6月 深圳语信公司
#写于2014年7月 深圳云雀公司
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/yun
export PATH
filepath=`pwd`
DATE=`date "+%Y%m%d%H%M" `
bootkernel=$1
cd $filepath
cp ~yun/mtk65xxrepack.pl .

./mtk65xxrepack.pl -recovery $bootkernel ~/yun/recoveryramdisk $DATE.img
rm mtk65xxrepack.pl