#!/bin/bash
#此脚本用来 DIY ROM 用
#制作者：陈云
#写于2014年3月 窝窝

PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

project=$1
DATE=`date "+%Y%m%d%H%M" `
filepath=`pwd`
echo "Signing.....$project"
java -jar ~/yun/signapk.jar ~/yun/testkey.x509.pem ~/yun/testkey.pk8 ${filepath}/${project} ${filepath}/${project}2
mv ${filepath}/${project} ${filepath}/${project}${DATE}
mv ${filepath}/${project}2 ${filepath}/${project}